version: "3.1"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    container_name: app-api
    image: node:18
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
    command: bash -c "npm install --omit=dev && npx prisma migrate dev && npx prisma generate && node dist/src/main/server.js"
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@database:5432/postgres"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
      - ./prisma/:/usr/src/app/prisma/
    links:
      - database
    depends_on:
      - database

volumes:
  postgres:
